version: 0.0
os: linux
files:
  - source: /
    destination: /opt/nginx
hooks:
  BeforeInstall:
    - location: install_docker.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_nginx.sh
      timeout: 300
      runas: root
